config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :words do
  	resources :definitions do 
      member do
        put "like", to: "definitions#upvote"
        put "dislike", to: "definitions#downvote"
      end
    end 
  	collection do
      get '/add-words',   to: 'words#new_word_multiple_form',     as: 'add'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'words#index'

end

app/models/definition.rb
class Definition < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :word

	self.per_page = 4

	acts_as_votable
	
	validates :definition, presence: true

end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :set_definition, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!
  before_action :set_word


  # GET /definitions
  # GET /definitions.json
  def index
    @definitions = Definition.all.order(:cached_votes_up => :desc)
  end

  # GET /definitions/1
  # GET /definitions/1.json
  def show
  end

  # GET /definitions/new
  def new
    @definition = Definition.new
  end

  # GET /definitions/1/edit
  def edit

  end

  # POST /definitions
  # POST /definitions.json
  def create
    @definition = Definition.new(definition_params)
    @definition.user_id = current_user.id
    @definition.word_id = @word.id

    respond_to do |format|
      if @definition.save
        format.html { redirect_to words_path, notice: 'Definition was successfully created.' }
        format.json { render :show, status: :created, location: @definition }
      else
        format.html { render :new }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definitions/1
  # PATCH/PUT /definitions/1.json
  def update
    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to word_path(@word), notice: 'Definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition }
      else
        format.html { render :edit }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    @definition.destroy
    respond_to do |format|
      format.html { redirect_to definitions_url, notice: 'Definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote 
    @definition.upvote_by current_user
    redirect_to word_path(@word)
  end  

  def downvote
    @definition.downvote_by current_user
    redirect_to word_path(@word)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_definition
      @definition = Definition.find(params[:id])
    end

    def set_word
      @word = Word.friendly.find(params[:word_id])
      #@word = Word.find_by_word(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def definition_params
      params.require(:definition).permit(:definition, :URL)
    end
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/views/definitions/_form.html.erb
<%= form_for([@word, @definition]) do |form| %>
  <% if definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(definition.errors.count, "error") %> prohibited this definition from being saved:</h2>

      <ul>
      <% definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h2><%= @word.word %></h2>
  </div>  

  <div class="form-group">
    <%= form.label :definition %>
    <%= form.text_area :definition, id: :definition_definition, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :URL %>
    <%= form.text_field :URL, id: :definition_URL, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/definitions/edit.html.erb
<h1>Editing Definition</h1>

<%= render 'form', definition: @definition %>

<%= link_to 'Definitions', word_path(@word) %>

app/views/definitions/index.html.erb
<%= link_to 'New Definition', new_word_definition_path %>

app/views/definitions/new.html.erb
<%= render 'form', definition: @definition %>

<%= link_to 'Back', words_path %>

app/views/definitions/show.html.erb
<p>
  <strong>Word:</strong>
  <%= @definition.word %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @definition.definition %>
</p>

<p>
  <strong>Url:</strong>
  <%= @definition.URL %>
</p>

<%= link_to 'Edit', edit_definition_path(@definition) %> |
<%= link_to 'Back', definitions_path %>