config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :words do
  	resources :definitions do 
      member do
        put "like", to: "definitions#upvote"
        put "dislike", to: "definitions#downvote"
      end
    end 
  	collection do
      get '/add-words',   to: 'words#new_word_multiple_form',     as: 'add'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'words#index'

end

app/models/word.rb
class Word < ApplicationRecord

	belongs_to :user
	#, optional: true
	has_many :definitions, dependent: :destroy
	
	accepts_nested_attributes_for :definitions
	#, reject_if: proc { |attributes| attributes[:definition].blank? }

	validates :word, presence: true

	self.per_page = 4

	acts_as_taggable_on :tags # Alias for acts_as_taggable_on :tags

	# def to_param
 #  	word
	# end

	extend FriendlyId
  friendly_id :word, use: :slugged

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  before_action :tag_cloud

  before_action :word_array

  # GET /words
  # GET /words.json
  def index
    #@words = Word.all.order('created_at DESC').paginate(:page => params[:page])
    #@definitions = @words.each  {|word| word.definitions.order(:cached_votes_up => :desc)}

    if params[:letter]
    @words = Word.all.order('created_at DESC').where("word like ?", params[:letter] +"%" ).paginate(:page => params[:page])
    # creates this /words?letter=i
    elsif params[:term]
    @words = Word.where('word LIKE ?', "%#{params[:term]}%").paginate(:page => params[:page])
    else
    @words = Word.all.order('created_at DESC').paginate(:page => params[:page])
    end

    respond_to do |format|
      format.html # will render index.html.erb in case of a HTML request
      format.js # will render index.js.erb in case of an AJAX request
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @definitions = @word.definitions.order(cached_votes_up: :desc, created_at: :desc)
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  def new_word_multiple_form

    @word = Word.new
    1.times { @word.definitions.build }
              #definition.create(definition: "stuff", word_id: @word)
              #word.definitions.build(definition: "stuff")
    @words = Word.all

  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create

    # From **new_word_multiple_form.html.erb**, there are TWO TABS submitting to words#create, 
    # if    #FIRST TAB in the form create a NEW @word and @definition.
        #     When creating a **NEW @word** the @word.id IS NIL, until after the save (when autoassigns .id)
    # else  #SECOND TAB in the form uses EXISTING @word and creates new @definition
        #     therefore, for EXISTING @word, params[:id] will exist, and be used
        #     (Note, create action for /words/:id/definitions/new) will also work here in the "else"

    if params[:id].nil? 
      @word = Word.new(word_params)
    else
      @word = Word.find(params[:id])
      @word.definitions.create!(definition: params[:word][:definitions_attributes]['0'][:definition])
    end
    # ...therefore, if @word IS NIL, 
    
    #@incoming_word = Word.new(word_params)
    #@word = Word.where(word: @incoming_word.word).first_or_create

    #@word = Word.where(word: word_params[:word]).first_or_create 

    #The first_or_create method checks whether first returns nil or not. 
    #If it does return nil, then create is called.


    @word.user_id = current_user.id

    #@word =  current_user.words.new(word_params)
    @word.definitions.each  {|definition| definition.user_id = current_user.id }

    respond_to do |format|
      if Word.where(word: word_params[:word]).present?
        format.html { redirect_to root_path, notice: 'Word already exists.' }
      elsif @word.save
        format.html { redirect_to root_path, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new_word_multiple_form }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to root_path, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tag_cloud
    @tag = Word.tag_counts_on(:tags).order('count desc').limit(17)
  end

  def word_array
    # Create array consisting of the first letter of every visitor's last name (word's word)
    @word_array = []
    @w = Word.all
    @w.each do |word|
        @word_array << word.word[0,1]
        end
    #Sort array alphabetically in ASC order
    @word_array.sort!
    #Remove duplicate elements
    @word_array.uniq!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.friendly.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word, :tag_list, definitions_attributes: [:definition, :URL])
    end
end

app/helpers/words_helper.rb
module WordsHelper
	 include ActsAsTaggableOn::TagsHelper
end

app/views/words/__definition_form.html.erb
<%= form_for @word do |form| %>

  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group upper-margin">
    <%= select_tag :word, options_for_select(Word.all.map { |word| [word.word, word.id] }), include_blank: "Word", class: "form-control"%>
  </div>

  <%= form.fields_for :definitions do |definition| %>

    <div class="form-group">
      <%= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
    </div>

  <% end %>

  <div class="form-group">
    <%= form.submit class: "btn btn-secondary form-control", value: "Create Definition" %>
  </div>

<% end %>

app/views/words/__form.html.erb
<%= form_for @word do |form| %>

  <% if word.errors.any? %>
<!--     <div id="error_explanation">
      <h2><%#= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <#% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <#% end %>
      </ul>
    </div> -->
    <% word.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "CodeUp Club Dictionary", sticky: false) %>
    <% end %>
  <% end %>


  <div class="form-group upper-margin">
    <%= form.text_field :word, id: :word_word, class: "form-control", placeholder: "Word" %>
  </div>

  <div class="form-group">
    <%= form.text_field :tag_list, value: @word.tag_list.to_s, class: "form-control", placeholder: "Tags (separated by commas)"  %>
  </div> 
  <!-- This form.fields_for section only appears if 
        the 1.times { @word.definitions.build } appears in the controller action.  
        or 
        In here instead of :definitions; form.fields_for(:definitions) is a method that only works when argument is present 
          - The argument that you're essentially passing in is @word.definitions.build 
          - behaves like an if statement: if the argument is passed in, the form renders, if not then not.
        -->
   <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
   
    <%= form.fields_for :definitions do |definition| %>
      <div class="form-group">

        <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
        <%= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
      </div>
    <% end %>

  <div class="form-group">
    <%= form.submit class: "btn btn-secondary form-control" %>
  </div>

<% end %>

app/views/words/_definition_form.html.erb
<%= form_for @word do |form| %>

  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group upper-margin">
    <%= select_tag :word, options_for_select(Word.all.map { |word| [word.word, word.id] }), include_blank: "Word", class: "form-control"%>
  </div>

  <%= form.fields_for :definitions do |definition| %>

    <div class="form-group">
      <%= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
    </div>

  <% end %>

  <div class="form-group">
    <%= form.submit class: "btn btn-secondary form-control", value: "Create Definition" %>
  </div>

<% end %>

app/views/words/_existing_word_new_definition_form.html.erb
<%#= render 'definition_form', word: @word %>

<%= form_for @word do |form| %>

<!--<#% if @word.errors.any? %> -->
<!--  <div id="error_explanation">
      <h2><%#= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <#% word.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <#% end %>
      </ul>
    </div> -->

  <div class="form-group upper-margin">
    <%= select_tag :id, #:id or :word_id (unsure)
        options_for_select(Word.all.map { |word| [word.word, word.id] }),
        include_blank: "Word",
        class: "form-control"%>

<!-- http://guides.rubyonrails.org/form_helpers.html#building-complex-forms -->
<%#= select_tag :word_id,     // (1) :id SAME AS <select name="city_id" id="city_id">
    options_for_select(Word.all.map { |word| [word.word, word.id] }, // (2) the <select> options
    selected: 3),             // (3) DO NOT USE HERE: this is the <select> option that is preselected. 
    include_blank: "Word",    // (4) Put "Word" as the default for the dropdown. Do #3 *OR* #4
    class: "form-control"%>
  </div>

  <%#= select_tag(:option, options_for_select([['All', 1], ['Co', 2], ['Bought', 3], ['View', 4], ['Top API', 5]], :selected => params[:option])) %>


  <%= form.fields_for :definitions do |definition| %>

    <div class="form-group">
      <%= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
    </div>

  <% end %>

  <div class="form-group">
    <%= form.submit class: "btn btn-secondary form-control", value: "Create Definition" %>
  </div>

<% end %>

app/views/words/_form.html.erb
<%= form_for @word do |form| %>

  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group upper-margin">
    <%= form.text_field :word, id: :word_word, class: "form-control", placeholder: "Word" %>
  </div>

  <div class="form-group">
    <%= form.text_field :tag_list, value: @word.tag_list.to_s, class: "form-control", placeholder: "Tags (separated by commas)"  %>
  </div> 
  <!-- This form.fields_for section only appears if 
        the 1.times { @word.definitions.build } appears in the controller action.  
        or 
        In here instead of :definitions; form.fields_for(:definitions) is a method that only works when argument is present 
          - The argument that you're essentially passing in is @word.definitions.build 
          - behaves like an if statement: if the argument is passed in, the form renders, if not then not.
        -->
         <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
         
         <%= logger.debug(@word.id ) %>

         <!-- 1. when button pressed for text area 
                  - submit form

               -->





  <%#= form.fields_for :definitions do |definition| %>
<!--     <div class="form-group">

      <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
      <%#= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
    </div>
  <%# end %> -->

  <div class="form-group">
    <%= form.submit class: "btn btn-secondary form-control" %>
  </div>

<% end %>

app/views/words/_new_word_new_definition_form.html.erb
<%#= render 'form', word: @word %>
 <%= form_for @word do |form| %>

  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

    <% @word.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %> 


  <div class="form-group upper-margin">
    <%= form.text_field :word, id: :word_word, class: "form-control", placeholder: "Word" %>
  </div>

  <div class="form-group">
    <%= form.text_field :tag_list, value: @word.tag_list.to_s, class: "form-control", placeholder: "Tags (separated by commas)"  %>
  </div> 
   
    <%= form.fields_for :definitions do |definition| %>
      <div class="form-group">

        <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
        <%= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
      </div>
    <% end %>

  <div class="form-group">
    <%= form.submit class: "btn btn-secondary form-control" %>
  </div>

<% end %>

app/views/words/_words.html.erb
<p><%= will_paginate @word, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %></p>

<!-- flex band -->
  <% @words.each do |word| %>
    <div class="band">
      <div class="two centered">
        <h5><%= link_to "#{word.word}", word %></h5>
        <p class="attribute"><%= word.user.first_name %> <%= word.user.last_name %>, <%= word.created_at.strftime("%-m/%-d/%-y") %> </p>
        
        <%= link_to new_word_definition_path(word) do %>
          <i class="fa fa-plus-square-o fa-lg" aria-hidden="true"></i>
        <% end %>

          <br>

          <!-- tags -->
        <div>
          <% word.tags.each do |tag| %>
            <span class="tag css4"><%= tag.name %></span>
          <% end %>
        </div>
      </div>

      <div class="three">

        <%#= will_paginate word.definitions %>

          <% word.definitions.order(:cached_votes_up => :desc).first(1).each do |definition| %>
            <div class="three-b">

              <div class="votes centered">
                <h5>Votes Tally:</h5>
                <br>
                <i class="fa fa-chevron-up" aria-hidden="true"></i>
                <h5><%= definition.cached_votes_up %></h5>
                <br>
                <h5><%= definition.cached_votes_down %></h5>
                <i class="fa fa-chevron-down" aria-hidden="true"></i>
              </div>

              <div class="definitions">
                  <h5><%= simple_format(definition.definition.gsub(/\\r\\n/, "\n")) %></h5>
                  <p class="attribute"><%= definition.user.first_name %> <%= definition.user.last_name %>, Submitted <%= time_ago_in_words(definition.created_at) %> ago. </p>
                  <div class="honeycomb"></div>
              </div>
            </div>
          <% end %>

            <div class="three-b">
              <div class="votes">
              </div>

              <div class="definitions">
                <h5><%= link_to "View all Definitions for #{word.word.capitalize}", word_path(word) %></h5>
              </div>

            </div>
        <%#= will_paginate word.definitions %>

      </div>

    </div>
  <% end %>
  <!-- end of flex band -->
<p><%= will_paginate @word, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %></p>

app/views/words/all_new.html.erb
<%#= render 'all_form', word: @word %>


<!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#word" role="tab">
      <h6>contribute new</h6><h5>WORD</h5><h6>with or w/o</h6><h5>DEFINITION</h5>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#definition" role="tab">
        <h6>select known word, to add</h6><h5>DEFINITION</h5>
      </a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="word" role="tabpanel">

      <%#= render 'form', word: @word %>

		 <%= form_for @word do |form| %>

		  <% if @word.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

		      <ul>
		      <% @word.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>

		    <!-- Gritter message instead of the error message -->

 		    <% @word.errors.full_messages.each do |error| %>
		      <%= alert_generator error %>
		    <% end %>
 		  <% end %> 
 

		  <div class="form-group upper-margin">
		    <%= form.text_field :word, id: :word_word, class: "form-control", placeholder: "Word" %>
		  </div>

		  <div class="form-group">
		    <%= form.text_field :tag_list, value: @word.tag_list.to_s, class: "form-control", placeholder: "Tags (separated by commas)"  %>
		  </div> 
		  <!-- This form.fields_for section only appears if 
		        the 1.times { @word.definitions.build } appears in the controller action.  
		        or 
		        In here instead of :definitions; form.fields_for(:definitions) is a method that only works when argument is present 
		          - The argument that you're essentially passing in is @word.definitions.build 
		          - behaves like an if statement: if the argument is passed in, the form renders, if not then not.
		        -->
		   
		    <%= form.fields_for :definitions do |definition| %>
		      <div class="form-group">

		        <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
		        <%= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
		      </div>
		    <% end %>

		  <div class="form-group">
		    <%= form.submit class: "btn btn-secondary form-control" %>
		  </div>

		<% end %>

    </div>
    
    <div class="tab-pane" id="definition" role="tabpanel">

      <%#= render 'definition_form', word: @word %>

			<%= form_for @word do |form| %>

<!-- 			  <#% if @word.errors.any? %>
 --><!-- 			    <div id="error_explanation">
			      <h2><%#= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

			      <ul>
			      <#% word.errors.full_messages.each do |message| %>
			        <li><%#= message %></li>
			      <#% end %>
			      </ul>
			    </div> -->

			    <!-- Gritter message instead of the error message -->

<!-- 		    	<#% word.errors.full_messages.each do |error| %>
			      <%#= js add_gritter(error, title: "CodeUp Club Dictionary", sticky: false) %>
			    <#% end %>
			  <#% end %> -->


			  <div class="form-group upper-margin">
			    <%= select_tag :word, options_for_select(Word.all.map { |word| [word.word, word.id] }, selected: params[:word]), include_blank: "Word", class: "form-control"%>
			  </div>

			  <%#= select_tag(:option, options_for_select([['All', 1], ['Co', 2], ['Bought', 3], ['View', 4], ['Top API', 5]], :selected => params[:option])) %>


			  <%= form.fields_for :definitions do |definition| %>

			    <div class="form-group">
			      <%= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
			    </div>

			  <% end %>

			  <div class="form-group">
			    <%= form.submit class: "btn btn-secondary form-control", value: "Create Definition" %>
			  </div>

			<% end %>

    </div>
  </div>

<%= link_to 'Back', words_path %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%#= render 'form', word: @word %>

<%= form_for @word do |form| %>

  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group upper-margin">
    <%= form.text_field :word, id: :word_word, class: "form-control", placeholder: "Word" %>
  </div>

  <div class="form-group">
    <%= form.text_field :tag_list, value: @word.tag_list.to_s, class: "form-control", placeholder: "Tags (separated by commas)"  %>
  </div> 
  <!-- This form.fields_for section only appears if 
        the 1.times { @word.definitions.build } appears in the controller action.  
        or 
        In here instead of :definitions; form.fields_for(:definitions) is a method that only works when argument is present 
          - The argument that you're essentially passing in is @word.definitions.build 
          - behaves like an if statement: if the argument is passed in, the form renders, if not then not.
        -->
<!--    <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button> -->
   
<!--     <%#= form.fields_for :definitions do |definition| %>
      <div class="form-group">

        <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
        <%#= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
      </div>
    <%# end %> -->

  <div class="form-group">
    <%= form.submit class: "btn btn-secondary form-control" %>
  </div>

<% end %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<div id="words_ajax"><%= render 'words' %></div>

app/views/words/index.js.erb
alert("this is an ajax request!")
$("#words_ajax").html("<%= escape_javascript(render('words')) %>")

app/views/words/new.html.erb
<%#= render 'form', word: @word %>

<%= form_for @word do |form| %>

  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group upper-margin">
    <%= form.text_field :word, id: :word_word, class: "form-control", placeholder: "Word" %>
  </div>

  <div class="form-group">
    <%= form.text_field :tag_list, value: @word.tag_list.to_s, class: "form-control", placeholder: "Tags (separated by commas)"  %>
  </div> 
  <!-- This form.fields_for section only appears if 
        the 1.times { @word.definitions.build } appears in the controller action.  
        or 
        In here instead of :definitions; form.fields_for(:definitions) is a method that only works when argument is present 
          - The argument that you're essentially passing in is @word.definitions.build 
          - behaves like an if statement: if the argument is passed in, the form renders, if not then not.
        -->
   <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
   
    <%= form.fields_for :definitions do |definition| %>
      <div class="form-group">

        <button type="button" id="ShiftButton" class="btn btn-secondary form-control" >I don't know the definition!</button>
        <%= definition.text_field :definition, class: "form-control definition", placeholder: "Definition", id: "chartdiv"%>
      </div>
    <% end %>

  <div class="form-group">
    <%= form.submit class: "btn btn-secondary form-control" %>
  </div>

<% end %>

<%= link_to 'Back', words_path %>

app/views/words/new_word_multiple_form.html.erb
<%#= render 'all_form', word: @word %>


<!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#word" role="tab">
      <h6>contribute new</h6><h5>WORD</h5><h6>with or w/o</h6><h5>DEFINITION</h5>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#definition" role="tab">
        <h6>select known word, to add</h6><h5>DEFINITION</h5>
      </a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <div class="tab-pane active" id="word" role="tabpanel">
      <%= render "new_word_new_definition_form" %>
    </div>
    
    <div class="tab-pane" id="definition" role="tabpanel">
      <%= render "existing_word_new_definition_form" %>
    </div>

  </div>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
    <%#= will_paginate word.definitions %>
    <div class="show">

      <div class="show-a">
        <div class="show-margin">
        </div>
        <div class="show-heading">
          <h5 class="edit"><%= @word.word %></h5>
            <div class="edit">
              <% if current_user.id == @word.user_id %>
                <%= link_to edit_word_path(@word) do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                <% end %>
                <%= link_to @word, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fa fa-trash-o" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </div>
        </div>
      </div>

      <% @definitions.each do |definition| %>

      <div class="show-b">

        <div class="show-votes centered">

          <!-- voting functionality -->
          <div>

            <p><%= link_to like_word_definition_path(@word, definition), method: :put do %>
              <i class="fa fa-arrow-up fa-lg" aria-hidden="true"></i>
            <% end %></p>
            
            <p><%= definition.get_upvotes.size %></p>
            
            <p><%= link_to dislike_word_definition_path(@word, definition), method: :put do %>
              <i class="fa fa-arrow-down fa-lg" aria-hidden="true"></i>
            <% end %></p>

          </div>
          <!-- end of voting functionality -->

        </div>

        <div class="show-definitions">
            <h5><%= simple_format(definition.definition.gsub(/\\r\\n/, "\n")) %></h5>
            <p class="attribute"><%= definition.user.first_name %> <%= definition.user.last_name %>, Submitted <%= time_ago_in_words(definition.created_at) %> ago.</p>
            <div class="edit">
              <% if current_user.id == definition.user_id %>
                <%= link_to edit_word_definition_path(@word, definition) do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                <% end %>
                <%= link_to @definition, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fa fa-trash-o" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </div>
            <div class="honeycomb"></div>
        </div>
      </div>

      <% end %>

    </div>
    <%#= will_paginate word.definitions %>





<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>