config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :words do
  	resources :definitions do 
      member do
        put "like", to: "definitions#upvote"
        put "dislike", to: "definitions#downvote"
      end
    end 
  	collection do
      get '/add-words',   to: 'words#new_word_multiple_form',     as: 'add'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'words#index'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded wrap">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div nav-brand centered>
    <h5>CodeUp Club</h5>
    <h4><%= link_to "Dictionary", root_path, class: "sub" %></h4>
  </div>
  <div class="collapse navbar-collapse vert-centered" id="navbarSupportedContent">
<!--     <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Browse <span class="sr-only">(current)</span></a>
      </li>
    </ul> -->
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Browse
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" data-turbolinks="false">
      <ul>

      <% if @word_array.present? %>

        <% @word_array.each do |letter| %>

<!--           <%#=  @word_array.inspect %>
 -->
          <!-- ["a", "i", "l", "n", "v"] -->

          <li class="dropdown-item"><%= link_to letter, :controller => "words" , :letter => letter %></li>

          <% end %>
        <% end %>
      </ul>
      </div>
    </div>
    <div class="box">
      <form class="form-inline my-2 my-lg-0 box-1 ml-auto">
<!--          <a class="ml-auto">
          <%#= link_to all_new_words_path, class: "nav-link overlay", style:"color:#5CB85C", data: { turbolinks: false }  do %>
           <i class="fa fa-plus-square-o fa-lg" aria-hidden="true"></i>
          <%# end %>
        </a> -->
        <div class="round-btn round-btn-outline-success ml-auto"><%= link_to "+", add_words_path, style:"color:#5CB85C", data: { turbolinks: false } %></div>

<!--         <input class="form-control mr-sm-2 ml-auto" type="text" placeholder="Search">
 --><!--         <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
 -->
        <%= form_tag(words_path, remote: true, method: :get, id: "words_search") do %>
          <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2 ml-auto", placeholder: "Search" %> <!-- to retain the term in the field add second parameter , params[:term] -->
          <%= submit_tag 'Search', class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>

      </form>
      <div class="box-2 ml-auto">
        <% if user_signed_in? %>
          <%= link_to 'Log Out', destroy_user_session_path, class: "links" %>
          <%= link_to 'Edit Account', edit_user_registration_path, class: "links" %>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "links" %>
          <%= link_to 'Sign In', new_user_session_path, class: "links" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DictionaryApp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- fonts -->
		<link href="https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada:700" rel="stylesheet">

    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    

  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <div class="wrap">

    </br>
    
  	<div class="container-fluid">

        <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>">
              <a href="#" data-dismiss="alert" class="close">×</a>
              <%= value %>
          </div>
        <% end %>


  		<%= yield %>


  	</div>
    
    </div>

  <%= alerts %>

  <script src="https://use.fontawesome.com/7315df07ae.js"></script>

  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

  </body>

</html>